ALTER TABLE app_users
	ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);

CREATE UNIQUE INDEX IF NOT EXISTS idx_app_users_local_email_unique
	ON app_users (LOWER(email))
	WHERE provider = 'local' AND email IS NOT NULL;

CREATE TABLE IF NOT EXISTS auth_refresh_tokens (
	id BIGSERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
	token_hash VARCHAR(128) NOT NULL UNIQUE,
	expires_at TIMESTAMPTZ NOT NULL,
	revoked_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE economy_metric_source_values
	ADD COLUMN IF NOT EXISTS raw_value VARCHAR(80) NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS raw_unit VARCHAR(80) NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS normalized_value VARCHAR(80) NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS normalized_unit VARCHAR(80) NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS comparison_note TEXT NOT NULL DEFAULT '';
