package com.junglecamp.backend.user;

import com.junglecamp.backend.user.model.AppUser;
import com.junglecamp.backend.user.service.AppUserService;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken;
import org.springframework.security.oauth2.core.user.DefaultOAuth2User;
import org.springframework.security.oauth2.core.user.OAuth2User;
import org.springframework.test.context.ActiveProfiles;
import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@ActiveProfiles("test")
class AppUserServiceTests {

	@Autowired
	private AppUserService appUserService;

	@Autowired
	private JdbcTemplate jdbcTemplate;

	@BeforeEach
	void resetUsers() {
		jdbcTemplate.execute("""
				CREATE TABLE IF NOT EXISTS app_users (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					provider VARCHAR(40) NOT NULL,
					provider_user_id VARCHAR(160) NOT NULL,
					email VARCHAR(320),
					display_name VARCHAR(160) NOT NULL,
					avatar_url VARCHAR(500),
					nickname VARCHAR(40),
					created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
					UNIQUE (provider, provider_user_id)
				)
				""");
		jdbcTemplate.update("DELETE FROM app_users");
	}

	@Test
	void upsertsGoogleUserByProviderUserId() {
		AppUser first = appUserService.upsertGoogleUser(
				"google-123",
				"user@example.com",
				"First Name",
				"https://example.com/a.png");

		AppUser second = appUserService.upsertGoogleUser(
				"google-123",
				"user@example.com",
				"Updated Name",
				"https://example.com/b.png");

		Integer userCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM app_users", Integer.class);

		assertThat(second.id()).isEqualTo(first.id());
		assertThat(second.provider()).isEqualTo("google");
		assertThat(second.providerUserId()).isEqualTo("google-123");
		assertThat(second.displayName()).isEqualTo("Updated Name");
		assertThat(second.avatarUrl()).isEqualTo("https://example.com/b.png");
		assertThat(userCount).isEqualTo(1);
	}

	@Test
	void currentUserReadsExistingGoogleUserWithoutRefreshingProfile() {
		appUserService.upsertGoogleUser(
				"google-123",
				"stored@example.com",
				"Stored Name",
				"https://example.com/stored.png");

		OAuth2User principal = new DefaultOAuth2User(
				List.of(new SimpleGrantedAuthority("ROLE_USER")),
				Map.of(
						"sub", "google-123",
						"email", "changed@example.com",
						"name", "Changed Name",
						"picture", "https://example.com/changed.png"),
				"sub");

		AppUser current = appUserService.currentUser(
				new OAuth2AuthenticationToken(principal, principal.getAuthorities(), "google"));

		assertThat(current.email()).isEqualTo("stored@example.com");
		assertThat(current.displayName()).isEqualTo("Stored Name");
		assertThat(current.avatarUrl()).isEqualTo("https://example.com/stored.png");
	}
}
