package com.junglecamp.backend.user;

import com.junglecamp.backend.user.model.AppUser;
import com.junglecamp.backend.user.service.AppUserService;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken;
import org.springframework.security.oauth2.core.OAuth2AuthenticationException;
import org.springframework.security.oauth2.core.user.DefaultOAuth2User;
import org.springframework.security.oauth2.core.user.OAuth2User;
import org.springframework.test.context.ActiveProfiles;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@SpringBootTest
@ActiveProfiles("test")
class AppUserServiceTests {

	@Autowired
	private AppUserService appUserService;

	@Autowired
	private JdbcTemplate jdbcTemplate;

	@BeforeEach
	void resetUsers() {
		jdbcTemplate.execute("""
				CREATE TABLE IF NOT EXISTS app_users (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					provider VARCHAR(40) NOT NULL,
					provider_user_id VARCHAR(160) NOT NULL,
					email VARCHAR(320),
					display_name VARCHAR(160) NOT NULL,
					avatar_url VARCHAR(500),
					nickname VARCHAR(40),
					created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
					UNIQUE (provider, provider_user_id)
				)
				""");
		jdbcTemplate.execute("ALTER TABLE app_users ADD COLUMN IF NOT EXISTS nickname VARCHAR(40)");
		jdbcTemplate.execute("ALTER TABLE app_users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255)");
		jdbcTemplate.execute("ALTER TABLE app_users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMP");
		jdbcTemplate.execute("ALTER TABLE app_users ADD COLUMN IF NOT EXISTS roles TEXT NOT NULL DEFAULT 'ROLE_USER'");
		jdbcTemplate.execute("ALTER TABLE app_users ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMP");
		jdbcTemplate.execute("ALTER TABLE app_users ADD COLUMN IF NOT EXISTS terms_accepted_at TIMESTAMP");
		jdbcTemplate.execute("ALTER TABLE app_users ADD COLUMN IF NOT EXISTS privacy_accepted_at TIMESTAMP");
		jdbcTemplate.execute("ALTER TABLE app_users ADD COLUMN IF NOT EXISTS marketing_opt_in BOOLEAN NOT NULL DEFAULT FALSE");
		jdbcTemplate.update("DELETE FROM app_users");
	}

	@Test
	void upsertsGoogleUserByProviderUserId() {
		AppUser first = appUserService.upsertGoogleUser(
				"google-123",
				"user@example.com",
				"First Name",
				"https://example.com/a.png");

		AppUser second = appUserService.upsertGoogleUser(
				"google-123",
				"user@example.com",
				"Updated Name",
				"https://example.com/b.png");

		Integer userCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM app_users", Integer.class);

		assertThat(second.id()).isEqualTo(first.id());
		assertThat(second.provider()).isEqualTo("google");
		assertThat(second.providerUserId()).isEqualTo("google-123");
		assertThat(second.displayName()).isEqualTo("Updated Name");
		assertThat(second.avatarUrl()).isEqualTo("https://example.com/b.png");
		assertThat(userCount).isEqualTo(1);
	}

	@Test
	void currentUserReadsExistingGoogleUserWithoutRefreshingProfile() {
		appUserService.upsertGoogleUser(
				"google-123",
				"stored@example.com",
				"Stored Name",
				"https://example.com/stored.png");

		OAuth2User principal = new DefaultOAuth2User(
				List.of(new SimpleGrantedAuthority("ROLE_USER")),
				Map.of(
						"sub", "google-123",
						"email", "changed@example.com",
						"name", "Changed Name",
						"picture", "https://example.com/changed.png"),
				"sub");

		AppUser current = appUserService.currentUser(
				new OAuth2AuthenticationToken(principal, principal.getAuthorities(), "google"));

		assertThat(current.email()).isEqualTo("stored@example.com");
		assertThat(current.displayName()).isEqualTo("Stored Name");
		assertThat(current.avatarUrl()).isEqualTo("https://example.com/stored.png");
	}

	@Test
	void rejectsNewGoogleUserWhenEmailBelongsToLocalAccount() {
		jdbcTemplate.update("""
				INSERT INTO app_users (
					provider, provider_user_id, email, display_name, avatar_url,
					nickname, password_hash, roles, email_verified_at
				) VALUES (
					'local', 'local@example.com', 'local@example.com', 'local_user', NULL,
					'local_user', 'encoded-password', 'ROLE_USER', CURRENT_TIMESTAMP
				)
				""");

		assertThatThrownBy(() -> appUserService.upsertGoogleUser(
						"google-new-123",
						"local@example.com",
						"Google Local",
						"https://example.com/google.png"))
				.isInstanceOfSatisfying(OAuth2AuthenticationException.class, exception ->
						assertThat(exception.getError().getErrorCode()).isEqualTo("local_email_exists"));

		Integer userCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM app_users", Integer.class);
		assertThat(userCount).isEqualTo(1);
	}
}
